/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import regrasDeNegocios.Despesa;
import dao.DespesaDao;
import dao.FuncionarioDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import regrasDeNegocios.Funcionario;
import utilitarios.ConexaoBD;
/**
 *
 * @author letic
 */
public class FormDespesa extends javax.swing.JDialog {
  Despesa ds = new Despesa();
  DespesaDao dsdao= new DespesaDao();
  String sql = "null";
    public FormDespesa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnCancelarL.setVisible(false);
        dsdao.checarDespesa();
        preencherTabela(sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1Fundo = new javax.swing.JLabel();
        jLabel1Fundo1 = new javax.swing.JLabel();
        painelGeralDespesa = new javax.swing.JTabbedPane();
        listar = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Despesa = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        btnCancelarL = new javax.swing.JButton();
        btRelatorio = new javax.swing.JButton();
        jLabel1Fundo2 = new javax.swing.JLabel();
        cadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeDesp = new javax.swing.JTextField();
        txtNumeroDocDespes = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIdDesp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValorDesp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDataDesp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1Fundo3 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        jLabel1Fundo.setBackground(new java.awt.Color(117, 64, 15));
        jLabel1Fundo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Fundo.setText("CAIXAAA");

        jLabel1Fundo1.setBackground(new java.awt.Color(117, 64, 15));
        jLabel1Fundo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Fundo1.setText("CAIXAAA");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DESPESA");
        setMinimumSize(new java.awt.Dimension(506, 406));
        setResizable(false);
        getContentPane().setLayout(null);

        painelGeralDespesa.setEnabled(false);
        painelGeralDespesa.setMinimumSize(new java.awt.Dimension(600, 600));

        listar.setLayout(null);

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        listar.add(txtPesquisa);
        txtPesquisa.setBounds(104, 28, 220, 36);

        btnNovo.setBackground(new java.awt.Color(117, 64, 15));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        listar.add(btnNovo);
        btnNovo.setBounds(10, 280, 80, 43);

        btnEditar.setBackground(new java.awt.Color(117, 64, 15));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        listar.add(btnEditar);
        btnEditar.setBounds(100, 280, 90, 43);

        btnExcluir.setBackground(new java.awt.Color(117, 64, 15));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        listar.add(btnExcluir);
        btnExcluir.setBounds(200, 280, 100, 43);

        jT_Despesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome ", "valor", "data", "numero documento", "Status Atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_Despesa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jT_Despesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_DespesaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_Despesa);

        listar.add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 470, 140);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pesquisar:");
        listar.add(jLabel7);
        jLabel7.setBounds(20, 36, 71, 17);

        btnPagar.setBackground(new java.awt.Color(117, 64, 15));
        btnPagar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("PAGAR");
        btnPagar.setEnabled(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        listar.add(btnPagar);
        btnPagar.setBounds(420, 280, 80, 43);

        btnCancelarL.setBackground(new java.awt.Color(117, 64, 15));
        btnCancelarL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelarL.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarL.setText("CANCELAR");
        btnCancelarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLActionPerformed(evt);
            }
        });
        listar.add(btnCancelarL);
        btnCancelarL.setBounds(310, 280, 100, 43);

        btRelatorio.setBackground(new java.awt.Color(117, 64, 15));
        btRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btRelatorio.setText("RELATÓRIO");
        btRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }
        });
        listar.add(btRelatorio);
        btRelatorio.setBounds(350, 20, 120, 43);

        jLabel1Fundo2.setBackground(new java.awt.Color(117, 64, 15));
        jLabel1Fundo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        jLabel1Fundo2.setText("CAIXAAA");
        listar.add(jLabel1Fundo2);
        jLabel1Fundo2.setBounds(0, 10, 500, 370);

        painelGeralDespesa.addTab("listar", listar);

        cadastro.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N° doc:");
        cadastro.add(jLabel1);
        jLabel1.setBounds(20, 250, 60, 17);

        txtNomeDesp.setEnabled(false);
        cadastro.add(txtNomeDesp);
        txtNomeDesp.setBounds(110, 110, 370, 30);

        txtNumeroDocDespes.setEnabled(false);
        cadastro.add(txtNumeroDocDespes);
        txtNumeroDocDespes.setBounds(110, 240, 290, 30);

        btnSalvar.setBackground(new java.awt.Color(117, 64, 15));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        cadastro.add(btnSalvar);
        btnSalvar.setBounds(30, 290, 98, 43);

        btnAtualizar.setBackground(new java.awt.Color(117, 64, 15));
        btnAtualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.setEnabled(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        cadastro.add(btnAtualizar);
        btnAtualizar.setBounds(180, 290, 115, 39);

        btnCancelar.setBackground(new java.awt.Color(117, 64, 15));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        cadastro.add(btnCancelar);
        btnCancelar.setBounds(340, 290, 110, 43);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID:");
        cadastro.add(jLabel8);
        jLabel8.setBounds(20, 60, 38, 31);

        txtIdDesp.setEditable(false);
        txtIdDesp.setEnabled(false);
        txtIdDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDespActionPerformed(evt);
            }
        });
        cadastro.add(txtIdDesp);
        txtIdDesp.setBounds(110, 60, 158, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor:");
        cadastro.add(jLabel3);
        jLabel3.setBounds(20, 200, 41, 30);

        txtValorDesp.setEnabled(false);
        cadastro.add(txtValorDesp);
        txtValorDesp.setBounds(110, 200, 110, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome:");
        cadastro.add(jLabel9);
        jLabel9.setBounds(20, 120, 46, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CADASTRO DE  DESPESA");
        cadastro.add(jLabel4);
        jLabel4.setBounds(210, 10, 186, 17);

        txtDataDesp.setEnabled(false);
        cadastro.add(txtDataDesp);
        txtDataDesp.setBounds(110, 160, 110, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("vencimento");
        cadastro.add(jLabel5);
        jLabel5.setBounds(20, 150, 80, 40);

        jLabel1Fundo3.setBackground(new java.awt.Color(117, 64, 15));
        jLabel1Fundo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Fundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        jLabel1Fundo3.setText("CAIXAAA");
        cadastro.add(jLabel1Fundo3);
        jLabel1Fundo3.setBounds(-10, -20, 560, 430);

        painelGeralDespesa.addTab("cadastro", cadastro);

        getContentPane().add(painelGeralDespesa);
        painelGeralDespesa.setBounds(0, 0, 660, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    if(!txtNomeDesp.getText().equals("")  && !txtValorDesp.getText().equals("")  && !txtDataDesp.getText().equals("")  && !txtNumeroDocDespes.getText().equals("")){
 

        ds.setDescricao_desp(txtNomeDesp.getText());
        ds.setValor_desp(Double.parseDouble(txtValorDesp.getText()));
        ds.setDatavencimento_desp(txtDataDesp.getText());
        ds.setNumerodoc_desp(txtNumeroDocDespes.getText());
        
        dsdao.inserir(ds);
        preencherTabela(sql);
        painelGeralDespesa.setSelectedIndex(0);
        cancelar();
        dsdao.checarDespesa();
        // vai mostrar qual painel da guia que eu quero voltar.
         }  else{
          JOptionPane.showMessageDialog(null,"PorFavor preencha todos os campos");
       }
       
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
           if(!txtNomeDesp.getText().equals("")  && !txtValorDesp.getText().equals("")  && !txtDataDesp.getText().equals("")  && !txtNumeroDocDespes.getText().equals("")){
        Despesa ds = new Despesa();
        ds.setId_despesa(Integer.parseInt(txtIdDesp.getText()));
        ds.setDescricao_desp(txtNomeDesp.getText());
        ds.setValor_desp(Double.parseDouble(txtValorDesp.getText()));
        ds.setDatavencimento_desp(txtDataDesp.getText());
        ds.setNumerodoc_desp(txtNumeroDocDespes.getText());
        ds.setValor_desp(Double.parseDouble (txtValorDesp.getText()));
        dsdao.atualizar(ds);
        dsdao.checarDespesa();
        preencherTabela(sql);
        painelGeralDespesa.setSelectedIndex(0);
         cancelar();
           }  else{
          JOptionPane.showMessageDialog(null,"PorFavor preencha todos os campos");
       }
       
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
       cancelar();
       desabilidarCampos();
       limparcampos();
       painelGeralDespesa.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIdDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDespActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        
        novo();
        habilidarCampos();
        limparcampos();
        painelGeralDespesa.setSelectedIndex(1);//volta pra primenira tela
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int opcao = jT_Despesa.getSelectedRow(); //Pega a lh selecionada que esta na tabela
        if(opcao>=0){
            
            ds.setId_despesa(Integer.parseInt(jT_Despesa.getValueAt(opcao,0).toString()));
            ds.setDescricao_desp(jT_Despesa.getValueAt(opcao, 1).toString());          
            dsdao.deletar(ds);
            preencherTabela(sql); // para atualizar tabela
            cancelar();
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");

        }
        
       

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int opcao = jT_Despesa.getSelectedRow(); //Pega a lh selecionada que esta na tabela
        if(opcao>=0){
          
            txtIdDesp.setText(jT_Despesa.getValueAt(opcao,0).toString());
            txtNomeDesp.setText(jT_Despesa.getValueAt(opcao, 1).toString()); // atribuindo um valor aos campos
            txtValorDesp.setText(jT_Despesa.getValueAt(opcao, 2).toString());
            txtDataDesp.setText(jT_Despesa.getValueAt(opcao, 3).toString());
            txtNumeroDocDespes.setText(jT_Despesa.getValueAt(opcao, 4).toString());
            painelGeralDespesa.setSelectedIndex(1);
            habilidarCampos();
            editar();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
         int opcao = jT_Despesa.getSelectedRow(); //Pega a lh selecionada que esta na tabela
        if(opcao>=0){
          
            ds.setId_despesa(Integer.parseInt(jT_Despesa.getValueAt(opcao,0).toString()));
            ds.setDescricao_desp(jT_Despesa.getValueAt(opcao, 1).toString());
            DespesaDao dsdao = new DespesaDao();
            dsdao.pagar(ds);
            preencherTabela(sql); // para atualizar tabela
            cancelar();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
       
    }//GEN-LAST:event_btnPagarActionPerformed

    private void jT_DespesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_DespesaMouseClicked
       clique();
       btnCancelarL.setVisible(true);
    }//GEN-LAST:event_jT_DespesaMouseClicked

    private void btnCancelarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLActionPerformed
        cancelar();
        btnCancelarL.setVisible(false);
    }//GEN-LAST:event_btnCancelarLActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
           preencherTabela("SELECT *FROM despesa where descricao_desp like '%"+txtPesquisa.getText()+"%'");
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioActionPerformed
            String sql = "select * from despesa";
        try{
    Map param = new HashMap();
     Connection con = ConexaoBD.getConectarBD();
    PreparedStatement prepare = con.prepareStatement(sql);
    ResultSet res = prepare.executeQuery();
            JRResultSetDataSource relatorioResult = new JRResultSetDataSource(res);
            JasperPrint jpPrint = JasperFillManager.fillReport("src/utilitarios/Cutelaria Artesanal Despesa.jasper", param,relatorioResult);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            jv.toFront();
            
    
    
    
  
       
    } catch (Exception ex) {
    JOptionPane.showMessageDialog(null,ex.getMessage());
    
    
  }
    }//GEN-LAST:event_btRelatorioActionPerformed
      public void preencherTabela(String sql){
    DespesaDao dsdao = new DespesaDao(); 
    List<Despesa> lista= dsdao.listarTodos(sql);
    DefaultTableModel tabela =  (DefaultTableModel) jT_Despesa.getModel();
    tabela.setRowCount(0);
    for(Despesa d: lista){
        tabela.addRow(new Object[]{ d.getId_despesa(), d.getDescricao_desp(), d.getValor_desp(), d.getDatavencimento_desp(), d.getNumerodoc_desp(),d.getStatusAtual_desp()});
    }
      }    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormDespesa dialog = new FormDespesa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
      
     public void cancelar(){
    btnNovo.setEnabled(true);
    btnSalvar.setEnabled(false);
    btnCancelar.setEnabled(false);
    btnEditar.setEnabled(false);
    btnExcluir.setEnabled(false);
    btnAtualizar.setEnabled(false);

     painelGeralDespesa.setEnabled(false);
     btnPagar.setEnabled(false);
     btnCancelarL.setVisible(false);
     }
     
    public void editar(){
    btnNovo.setEnabled(false);
    btnSalvar.setEnabled(false);
    btnCancelar.setEnabled(true);
    btnEditar.setEnabled(false);
    btnAtualizar.setEnabled(true);
    btnExcluir.setEnabled(false);
       }
    
    
      public void novo(){
    btnNovo.setEnabled(false);
    btnSalvar.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnEditar.setEnabled(false);
    btnExcluir.setEnabled(false);

    btnPagar.setEnabled(false);
    painelGeralDespesa.setEnabled(true);
    }
    public void clique(){
    btnCancelar.setEnabled(true);
    btnSalvar.setEnabled(false);
    btnNovo.setEnabled(false);
    btnEditar.setEnabled(true);
    btnExcluir.setEnabled(true);

     btnPagar.setEnabled(true);
    
    }
       public void habilidarCampos(){
   
    txtNomeDesp.setEnabled(true);
    txtValorDesp.setEnabled(true);
    txtDataDesp.setEnabled(true);
    txtNumeroDocDespes.setEnabled(true);
    }
    public void desabilidarCampos(){
    
    txtNomeDesp.setEnabled(false);
    txtValorDesp.setEnabled(false);
    txtDataDesp.setEnabled(false);
    txtNumeroDocDespes.setEnabled(false);
    }
    public void limparcampos(){
       txtIdDesp.setText(null);
        txtNomeDesp.setText(null);
        txtDataDesp.setText(null);
        txtNumeroDocDespes.setText(null);
        txtValorDesp.setText(null);
    }
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRelatorio;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarL;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel cadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Fundo;
    private javax.swing.JLabel jLabel1Fundo1;
    private javax.swing.JLabel jLabel1Fundo2;
    private javax.swing.JLabel jLabel1Fundo3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jT_Despesa;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel listar;
    private javax.swing.JTabbedPane painelGeralDespesa;
    private javax.swing.JTextField txtDataDesp;
    private javax.swing.JTextField txtIdDesp;
    private javax.swing.JTextField txtNomeDesp;
    private javax.swing.JTextField txtNumeroDocDespes;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtValorDesp;
    // End of variables declaration//GEN-END:variables


}
