/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.FornecedorDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import dao.ProdutoDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import regrasDeNegocios.Fornecedor;
import regrasDeNegocios.Produto;
import utilitarios.ConexaoBD;


/**
 *
 * @author Igreja Ass Deus
 */
public class FormProduto extends javax.swing.JFrame {
    String sql = "null";
    ProdutoDao prdao= new ProdutoDao();
    Produto p = new Produto();
     int x=0;// quando o botao estoque for precionado o valor de x se torna 1 quando fechar a tela de estoque e produto ganhar o foco a tela vai preencher a tabela com o registro atualizado
        public FormProduto() {
        initComponents();
        preencherTabela(sql);
        preencherCbFornecedor();
        btnCancelarL.setVisible(false);
        
       
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zxc = new javax.swing.JPanel();
        painelGeralProduto = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Produto = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnEstoque = new javax.swing.JButton();
        btnCancelarL = new javax.swing.JButton();
        btRelatorio = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDescriçãoProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidadeProd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMarcaProd = new javax.swing.JTextField();
        cbFornecedor = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        btnNovoFornecedor = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtValorProd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1Fundo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produto");

        painelGeralProduto.setEnabled(false);
        painelGeralProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        painelGeralProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelGeralProdutoMouseEntered(evt);
            }
        });

        jPanel3.setLayout(null);

        tabela_Produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "descriçao ", "marca", "quantidade", "valor", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_Produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_ProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_Produto);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 71, 560, 220);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pesquisar POR NOME:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 36, 152, 17);

        btnNovo.setBackground(new java.awt.Color(117, 64, 15));
        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNovo);
        btnNovo.setBounds(20, 310, 80, 43);

        btnEditar.setBackground(new java.awt.Color(117, 64, 15));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar);
        btnEditar.setBounds(110, 310, 87, 43);

        btnExcluir.setBackground(new java.awt.Color(117, 64, 15));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(btnExcluir);
        btnExcluir.setBounds(220, 310, 100, 43);

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        jPanel3.add(txtPesquisa);
        txtPesquisa.setBounds(170, 30, 250, 28);

        btnEstoque.setBackground(new java.awt.Color(117, 64, 15));
        btnEstoque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btnEstoque.setText("ESTOQUE");
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });
        jPanel3.add(btnEstoque);
        btnEstoque.setBounds(340, 310, 90, 43);

        btnCancelarL.setBackground(new java.awt.Color(117, 64, 15));
        btnCancelarL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelarL.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarL.setText("CANCELAR");
        btnCancelarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelarL);
        btnCancelarL.setBounds(450, 310, 100, 43);

        btRelatorio.setBackground(new java.awt.Color(117, 64, 15));
        btRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btRelatorio.setText("Relatório");
        btRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }
        });
        jPanel3.add(btRelatorio);
        btRelatorio.setBounds(440, 20, 120, 43);

        Fundo.setForeground(new java.awt.Color(255, 255, 255));
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        Fundo.setText("CAIXAAA");
        jPanel3.add(Fundo);
        Fundo.setBounds(0, 0, 620, 420);

        painelGeralProduto.addTab("Listar", jPanel3);

        jPanel2.setLayout(null);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 206, 0, 0);

        txtDescriçãoProd.setEnabled(false);
        jPanel2.add(txtDescriçãoProd);
        txtDescriçãoProd.setBounds(130, 90, 380, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modelo:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 140, 55, 17);

        btnSalvar.setBackground(new java.awt.Color(117, 64, 15));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(30, 350, 98, 43);

        btnAtualizar.setBackground(new java.awt.Color(117, 64, 15));
        btnAtualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.setEnabled(false);
        btnAtualizar.setMaximumSize(new java.awt.Dimension(89, 25));
        btnAtualizar.setMinimumSize(new java.awt.Dimension(89, 25));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtualizar);
        btnAtualizar.setBounds(200, 350, 115, 43);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 50, 38, 31);

        txtIdProd.setEditable(false);
        txtIdProd.setEnabled(false);
        txtIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProdActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdProd);
        txtIdProd.setBounds(130, 50, 150, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fornecedor");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 250, 100, 30);

        txtQuantidadeProd.setEnabled(false);
        jPanel2.add(txtQuantidadeProd);
        txtQuantidadeProd.setBounds(130, 210, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 90, 46, 30);

        txtMarcaProd.setEnabled(false);
        txtMarcaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaProdActionPerformed(evt);
            }
        });
        jPanel2.add(txtMarcaProd);
        txtMarcaProd.setBounds(130, 130, 190, 32);

        cbFornecedor.setEnabled(false);
        jPanel2.add(cbFornecedor);
        cbFornecedor.setBounds(130, 250, 230, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Valor:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 170, 50, 30);

        btnNovoFornecedor.setBackground(new java.awt.Color(117, 64, 15));
        btnNovoFornecedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnNovoFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoFornecedor.setText("NOVO FORNECEDOR");
        btnNovoFornecedor.setEnabled(false);
        btnNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnNovoFornecedor);
        btnNovoFornecedor.setBounds(370, 250, 140, 30);

        btnCancelar.setBackground(new java.awt.Color(117, 64, 15));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(380, 350, 130, 43);

        txtValorProd.setEnabled(false);
        jPanel2.add(txtValorProd);
        txtValorProd.setBounds(130, 170, 110, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("quantidade");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 210, 90, 30);

        jLabel1Fundo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Fundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        jLabel1Fundo3.setText("CAIXAAA");
        jPanel2.add(jLabel1Fundo3);
        jLabel1Fundo3.setBounds(0, 0, 610, 460);

        painelGeralProduto.addTab("Cadastro", jPanel2);

        javax.swing.GroupLayout zxcLayout = new javax.swing.GroupLayout(zxc);
        zxc.setLayout(zxcLayout);
        zxcLayout.setHorizontalGroup(
            zxcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zxcLayout.createSequentialGroup()
                .addComponent(painelGeralProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        zxcLayout.setVerticalGroup(
            zxcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zxcLayout.createSequentialGroup()
                .addComponent(painelGeralProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(zxc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zxc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        habilidarCampos();
        limparcampos();
        novo();
        painelGeralProduto.setSelectedIndex(1);//volta pra primenira tela
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int opcao = tabela_Produto.getSelectedRow(); //Pega a lh selecionada que esta na tabela
        if(opcao>=0){
            txtIdProd.setText(tabela_Produto.getValueAt(opcao,0).toString());
            txtDescriçãoProd.setText(tabela_Produto.getValueAt(opcao, 1).toString()); // atribuindo um valor aos campos
            txtMarcaProd.setText(tabela_Produto.getValueAt(opcao, 2).toString());
            txtQuantidadeProd.setText(tabela_Produto.getValueAt(opcao, 3).toString());
            txtValorProd.setText(tabela_Produto.getValueAt(opcao, 4).toString());
            cbFornecedor.setSelectedItem(tabela_Produto.getValueAt(opcao, 5).toString());
            habilidarCampos();
            txtQuantidadeProd.setEnabled(false);
            editar();
            painelGeralProduto.setSelectedIndex(1);
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
    if(!txtDescriçãoProd.getText().equals("")  && !txtMarcaProd.getText().equals("")  &&  !txtQuantidadeProd.getText().equals("") &&  !txtValorProd.getText().equals("")  ){

        // TODO add your handling code here:
        Produto pr = new Produto();
        pr.setId_produto(Integer.parseInt(txtIdProd.getText()));
        pr.setDescricao_prod(txtDescriçãoProd.getText());     
        pr.setMarca_prod(txtMarcaProd.getText());
        pr.setQuant_prod(Integer.parseInt(txtQuantidadeProd.getText()));
        pr.setValor_prod(Float.parseFloat (txtValorProd.getText()));
        Fornecedor f = (Fornecedor) cbFornecedor.getSelectedItem();
        pr.setFornecedor(f);
        prdao.atualizar(pr);
        preencherTabela(sql);
        painelGeralProduto.setSelectedIndex(0);
        cancelar();
         }else{
          JOptionPane.showMessageDialog(null,"PorFavor preencha todos os campos");
       }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
if(!txtDescriçãoProd.getText().equals("")  && !txtMarcaProd.getText().equals("")  &&  !txtQuantidadeProd.getText().equals("") &&  !txtValorProd.getText().equals("")  ){

        // TODO add your handling code here:
        Produto pr = new Produto();

        pr.setDescricao_prod(txtDescriçãoProd.getText());
        pr.setMarca_prod(txtMarcaProd.getText());
        pr.setQuant_prod(Integer.parseInt(txtQuantidadeProd.getText()));
        pr.setValor_prod(Float.parseFloat(txtValorProd.getText()));
        Fornecedor f = (Fornecedor) cbFornecedor.getSelectedItem();
        pr.setFornecedor(f);
        prdao.inserir(pr);
        
        preencherTabela(sql);
        painelGeralProduto.setSelectedIndex(0);
        cancelar();
        // vai mostrar qual painel da guia que eu quero voltar.
         }else{
          JOptionPane.showMessageDialog(null,"PorFavor preencha todos os campos");
       }
     
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtMarcaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaProdActionPerformed

    private void txtIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdActionPerformed

    private void btnNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFornecedorActionPerformed
      FormFornecedor form = new FormFornecedor(this, rootPaneCheckingEnabled);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
        x=1;
    }//GEN-LAST:event_btnNovoFornecedorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
        desabilidarCampos();
        limparcampos();
        painelGeralProduto.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        x = 1;
        FormEstoque form = new FormEstoque(this, rootPaneCheckingEnabled);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void tabela_ProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_ProdutoMouseClicked
        clique();
       btnCancelarL.setVisible(true);
    }//GEN-LAST:event_tabela_ProdutoMouseClicked

    private void btnCancelarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLActionPerformed
        cancelar();
        btnCancelarL.setVisible(false);
    }//GEN-LAST:event_btnCancelarLActionPerformed

    private void painelGeralProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelGeralProdutoMouseEntered
       if (x==1){
           preencherTabela(sql);
           cbFornecedor.removeAllItems();
           preencherCbFornecedor();
           x=0;
        }  // TODO add your handling code here:
    }//GEN-LAST:event_painelGeralProdutoMouseEntered

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
   preencherTabela("SELECT * FROM Produto INNER Join fornecedor on fornecedor.id_fornecedor = produto.id_fornecedor where descricao_prod like'%"+txtPesquisa.getText()+"%'");
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int opcao = tabela_Produto.getSelectedRow(); //Pega a lh selecionada que esta na tabela
        if(opcao>=0){
            Produto p = new Produto();
            p.setId_produto(Integer.parseInt(tabela_Produto.getValueAt(opcao,0).toString()));
            p.setDescricao_prod(tabela_Produto.getValueAt(opcao, 1).toString());
            prdao.deletar(p);
            preencherTabela(sql);
            cancelar(); // para atualizar tabela
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");

        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioActionPerformed
        // TODO add your handling code here:
                String sql = "SELECT\n" +
"     *,\n" +
"     fornecedor.`id_fornecedor` AS fornecedor_id_fornecedor,\n" +
"     fornecedor.`nome_for` AS fornecedor_nome_for,\n" +
"     fornecedor.`cnpj_for` AS fornecedor_cnpj_for,\n" +
"     fornecedor.`telefone_for` AS fornecedor_telefone_for,\n" +
"     fornecedor.`endereco_for` AS fornecedor_endereco_for\n" +
"FROM\n" +
"     `fornecedor` fornecedor INNER JOIN `produto` produto ON fornecedor.`id_fornecedor` = produto.`id_fornecedor`";
        try{
    Map param = new HashMap();
     Connection con = ConexaoBD.getConectarBD();
    PreparedStatement prepare = con.prepareStatement(sql);
    ResultSet res = prepare.executeQuery();
            JRResultSetDataSource relatorioResult = new JRResultSetDataSource(res);
            JasperPrint jpPrint = JasperFillManager.fillReport("src/utilitarios/Cutelaria Artesanal Produto.jasper", param,relatorioResult);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            jv.toFront();
            
 
    } catch (Exception ex) {
    JOptionPane.showMessageDialog(null,ex.getMessage());
    }
    }//GEN-LAST:event_btRelatorioActionPerformed

    public void preencherTabela(String sql){
   
    List<Produto> lista= prdao.listarTodos(sql);
    DefaultTableModel tabela = (DefaultTableModel) tabela_Produto.getModel();
    tabela.setRowCount(0);
    for(Produto p: lista){
        tabela.addRow(new Object[]{p.getId_produto(), p.getDescricao_prod(), p.getMarca_prod(), p.getQuant_prod(), p.getValor_prod(),p.getFornecedor().getNome_for()});
    }
    
    }
      public void preencherCbFornecedor(){
        FornecedorDao edao = new FornecedorDao();
        List<Fornecedor> lista = edao.listarTodos(sql);
        for (Fornecedor e : lista){
            cbFornecedor.addItem(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProduto().setVisible(true);
            }
        });
    }

    
     public void cancelar(){
    btnNovo.setEnabled(true);
    btnSalvar.setEnabled(false);
    btnCancelar.setEnabled(false);
    btnEditar.setEnabled(false);
    btnExcluir.setEnabled(false);
    btnAtualizar.setEnabled(false);
    btnCancelarL.setVisible(false);
    painelGeralProduto.setEnabled(false);
     }
     
    public void editar(){
    btnNovo.setEnabled(false);
    btnSalvar.setEnabled(false);
    btnCancelar.setEnabled(true);
    btnEditar.setEnabled(false);
    btnAtualizar.setEnabled(true);
    btnExcluir.setEnabled(false);
     painelGeralProduto.setEnabled(true);
    }
    
    
      public void novo(){
    btnNovo.setEnabled(false);
    btnSalvar.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnEditar.setEnabled(false);
    btnExcluir.setEnabled(false);
     btnNovoFornecedor.setEnabled(true);
     painelGeralProduto.setEnabled(true);
    }
    public void clique(){
    btnCancelar.setEnabled(true);
    btnSalvar.setEnabled(false);
    btnNovo.setEnabled(false);
    btnEditar.setEnabled(true);
    btnExcluir.setEnabled(true);

    }
       public void habilidarCampos(){
  
    txtDescriçãoProd.setEnabled(true);
    txtMarcaProd.setEnabled(true);
    txtQuantidadeProd.setEnabled(true);
    txtValorProd.setEnabled(true);
    cbFornecedor.setEnabled(true);
    
    }
    public void desabilidarCampos(){
   
    txtDescriçãoProd.setEnabled(false);
    txtMarcaProd.setEnabled(false);
    txtQuantidadeProd.setEnabled(false);
    txtValorProd.setEnabled(false);
    cbFornecedor.setEnabled(false);
    
    }
    public void limparcampos(){
        txtIdProd.setText(null);
        txtDescriçãoProd.setText(null);
        txtMarcaProd.setText(null);
        txtQuantidadeProd.setText(null);
        txtValorProd.setText(null);
        
    }
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton btRelatorio;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarL;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovoFornecedor;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbFornecedor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1Fundo3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane painelGeralProduto;
    private javax.swing.JTable tabela_Produto;
    private javax.swing.JTextField txtDescriçãoProd;
    private javax.swing.JTextField txtIdProd;
    private javax.swing.JTextField txtMarcaProd;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtQuantidadeProd;
    private javax.swing.JTextField txtValorProd;
    private javax.swing.JPanel zxc;
    // End of variables declaration//GEN-END:variables
}
