/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.CaixaDao;
import dao.FuncionarioDao;
import java.awt.Menu;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import regrasDeNegocios.Funcionario;
import regrasDeNegocios.Cliente;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
FuncionarioDao fcdao= new FuncionarioDao();
    Funcionario usuario = new Funcionario();
    boolean x = false;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setIconImage(new ImageIcon("logo-ifro.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Jf_cpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jp_senha = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BEM VINDO A CUTELARIA ARTESANAL 1.0");
        setMaximumSize(new java.awt.Dimension(500, 250));
        setMinimumSize(new java.awt.Dimension(500, 250));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 250));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("        CPF:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 10, 96, 22);

        try {
            Jf_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Jf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jf_cpfActionPerformed(evt);
            }
        });
        jPanel2.add(Jf_cpf);
        Jf_cpf.setBounds(277, 34, 210, 36);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SENHA:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(350, 70, 80, 22);

        jButton2.setBackground(new java.awt.Color(117, 64, 15));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(390, 160, 100, 35);

        jLabel4.setText("Esqueceu a senha?");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(330, 209, 109, 16);

        jp_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_senhaActionPerformed(evt);
            }
        });
        jp_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jp_senhaKeyReleased(evt);
            }
        });
        jPanel2.add(jp_senha);
        jp_senha.setBounds(277, 99, 210, 41);

        jButton3.setBackground(new java.awt.Color(117, 64, 15));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ENTRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(280, 160, 86, 35);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 10, 240, 230);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("versão: 1.0");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(200, 220, 90, 20);

        Fundo.setForeground(new java.awt.Color(255, 255, 255));
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        Fundo.setText("CAIXAAA");
        jPanel2.add(Fundo);
        Fundo.setBounds(0, 0, 610, 460);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 508, 250);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jp_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_senhaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      login();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void Jf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jf_cpfActionPerformed

    private void jp_senhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jp_senhaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        login();
            
        }
    }//GEN-LAST:event_jp_senhaKeyReleased

    
    
    private void login(){
        
        usuario.setCpf_func(Jf_cpf.getText());
        usuario.setSenha_func(String.valueOf(jp_senha.getPassword()));
        fcdao.login(usuario);
     
     if (usuario.getId_funcionario()> 0){
         CaixaDao cdao = new CaixaDao();
         x= cdao.checarSaldoCaixa();
         
         if (x==true){
         FormMenu m = new FormMenu();
         m.setVisible(true);
         this.dispose();
      }
     }else{
           JOptionPane.showMessageDialog(null, "USUÁRIO OU SENHA INCORRETO! ");
     }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JFormattedTextField Jf_cpf;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPasswordField jp_senha;
    // End of variables declaration//GEN-END:variables
}
